galaxy_info:
  role_name: google_chrome
  author: KIKUCHI Koichiro
  description: ansible role to install Google Chrome
  license: BSD
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - 7
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []

dependencies: []
